version: '3.9'

networks:
  app-network:
    driver: bridge

services:
  app-database:
    image: postgres
    restart: always
    networks:
      - 'app-network'
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./database/postgres:/database/postgres
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  app-backend:
    build: .
    restart: always
    networks:
      - 'app-network'
    ports:
      - 3333:3333
    volumes:
      - ./src:/app/backend/src
    links:
      - app-database
    depends_on:
      - app-database
